//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJobSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyTable
    {
        public int application_id { get; set; }
        public int user_id { get; set; }
        public int company_id { get; set; }
        public int job_id { get; set; }
        public string app_resume { get; set; }
        public System.DateTime apply_date { get; set; }
        public string application_status { get; set; }
    }
}
