//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJobSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyTab
    {
        public int company_id { get; set; }
        public string company_name { get; set; }
        public string company_address { get; set; }
        public long company_phone { get; set; }
        public string company_email { get; set; }
        public string company_website { get; set; }
        public string company_location { get; set; }
    }
}
