//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJobSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobstable
    {
        public int job_id { get; set; }
        public int company_id { get; set; }
        public string job_title { get; set; }
        public string job_experience { get; set; }
        public string job_skills { get; set; }
        public int job_vacancy { get; set; }
        public System.DateTime job_date { get; set; }
        public string job_status { get; set; }
    }
}
