//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJobSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTab
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public int user_age { get; set; }
        public string user_address { get; set; }
        public long user_phone { get; set; }
        public string user_email { get; set; }
        public string user_qualification { get; set; }
        public string user_skills { get; set; }
        public int user_experience { get; set; }
        public string user_resume { get; set; }
    }
}
